# Generated by Django 3.0.4 on 2020-03-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed')], default='OP', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_close_date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='updated_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
