# Generated by Django 3.0.4 on 2020-03-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_auto_20200328_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_close_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
