# Generated by Django 3.0.4 on 2020-04-02 04:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0005_auto_20200329_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeaction',
            name='action_executed_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 2, 4, 37, 53, 347074, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradeaction',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_set', to='oj.Trade'),
        ),
    ]
