# Generated by Django 3.0.4 on 2020-04-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0006_auto_20200402_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeaction',
            name='action_type',
            field=models.CharField(choices=[('OPN', 'Open'), ('ADJ', 'Adjustment'), ('CLS', 'Close')], max_length=50),
        ),
    ]
